---
# Do not change the version, this can lead to deletion of the file
version: "1.1.0"

# Available languages: eng, deu, kor
lang: "kor"

# Available providers: yaml
provider: "yaml"

# How many plots a player can own
max-plots: 2

# Determine if you should be teleported to the plot border when the plot is claimed
teleport-on-claim: true

# Whether the popup should appear when you enter a plot
show-popup: true

# Decide here whether Economy should be used for claiming, emptying and deleting plots
economy: false

# Here you find the plot configurations,
# how the plot world should look like later, when the world is generated for the first time
default-settings:
  plotSize: 32
  roadBlock: "5:0"
  wall:
    unclaimed: "44:0"
    claimed: "44:1"
  bottomBlock: "7:0"
  plotFloorBlock: "2:0"
  plotFillBlock: "3:0"
  roadWidth: 7
  groundHeight: 64
  price:
    claim: 500
    clear: 300
    delete: 200
    dispose: 500
...
